Fix Helm chart kubeVersion comparison error
Fixes this error when trying to install the chart:

> $ helm upgrade --install vals-operator ./vals-operator-0.5.0.tgz
> Release "vals-operator" does not exist. Installing it now.
> Error: chart requires kubeVersion: >= 1.19 which is incompatible with Kubernetes v1.21.5-eks-bc4871b

The issue and solution is described here:
https://github.com/helm/helm/issues/3810

In addition, the duplicate `kubeVersion` field was removed.